FROM golang:1.10 AS build_stage

WORKDIR /go/src/app

RUN go get -u github.com/golang/dep/cmd/dep
COPY . .

RUN dep ensure
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o prockiller .

FROM gcr.io/cloudsql-docker/gce-proxy:1.11

COPY --from=build_stage /go/src/app/prockiller .
